language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libjson-perl
            - astyle
      before_script:
        - make astyle-check
        - make lint-check

    - os: linux
      env: TILES=1 SOUND=1 LUA=1
      compiler: gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-ttf-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - lua5.1
            - liblua5.1-0-dev

    - os: osx
      env: LOCALIZE=0
      compiler: clang

    - env: LOCALIZE=0
      addons:
        apt:
          packages:
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
      before_script:
        - export CXX=i686-w64-mingw32-g++

script:
  - make
