language: cpp
sudo: required
dist: trusty

cache:
  ccache: true
  directories:
    - ./obj

before_install:
  - git diff --quiet master .travis.yml
  - git diff --quiet master Makefile
  - git diff --quiet master tools/format/format.pl

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjson-perl astyle
  - sudo apt-get install -y lua5.1 liblua5.1-0-dev
  - sudo apt-get install -y jq

matrix:
  include:
    - env:

    - env: TILES=1 SOUND=1 LUA=1
      before_script:
        - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev

    - env: NATIVE=win32 CROSS=i686-w64-mingw32-
      before_script:
        - sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686

    - env: NATIVE=win32 CROSS=i686-w64-mingw32- TILES=1 SOUND=1 LUA=1
      before_script:
        - sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686

script:
  - for file in `find data/json/ -type f -regex ".*\.json$"`; do echo $file; jq '.' $file > /dev/null || exit 65; done
  - make astyle-check
  - make lint-check
  - make
