branches:
  only:
    - master

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libjson-perl
      - astyle

language: cpp

matrix:
  include:
    -os: linux
     compiler: gcc

    -os: linux
     compiler: gcc
     env: TILES=1
     addons:
       apt:
         packages:
           - libsdl2

    -os: osx
     compiler: clang

script:
  - make astyle-check
  - make lint-check
  - make LOCALIZE=0
