branches:
  only:
    - master

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjson-perl astyle

script:
  - make astyle-check
  - make lint-check
  - make
