branches:
  only:
    - master

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libjson-perl
      - astyle

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - make astyle-check
  - make lint-check
  - make
