branches:
  only:
    - master

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libjson-perl
      - astyle

language: cpp

cache:
  - ccache

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - make astyle-check
  - make lint-check
  - make CCACHE=1 LOCALIZE=0
