branches:
  only:
    - master

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libjson-perl
      - astyle

language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      

    - compiler: gcc
      os: linux
      env: TILES=1
      addons:
        apt:
          packages:
            - libsdl2

    - compiler: clang
      os: osx

script:
  - make astyle-check
  - make lint-check
  - make LOCALIZE=0
