branches:
  only:
    - master

sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
        packages:
          - libjson-perl
          - astyle
      before_script:
        - make astyle-check
        - make lint-check

    - os: linux
      env: TILES=1
      compiler: gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-ttf-dev
            - libsdl2-image-dev

    - os: osx
      env: LOCALIZE=0
      compiler: clang

script:
  - make RELEASE=1
