language: cpp
cache: ccache

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libjson-perl
            - astyle
      before_script:
        - make astyle-check
        - make lint-check

    - os: linux
      env: TILES=1 SOUND=1 LUA=1
      compiler: gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-ttf-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - lua5.1
            - liblua5.1-0-dev

    - env: NATIVE=win32 CROSS=i686-w64-mingw32- CXXFLAGS="-I./WinDepend/include" LDFLAGS="-L./WinDepend/lib"
      addons:
        apt:
          packages:
            - p7zip-full
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
      before_script:
        - 7z x cdda-win64-codeblocks.7z

    - env: NATIVE=win32 CROSS=i686-w64-mingw32- CXXFLAGS="-I./WinDepend/include -I./WinDepend/include/SDL2" LDFLAGS="-L./WinDepend/lib" TILES=1
      addons:
        apt:
          packages:
            - p7zip-full
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
      before_script:
        - 7z x cdda-win64-codeblocks.7z
      script:
          make -DLIBINTL_STATIC=1

    - os: osx
      env: LOCALIZE=0
      compiler: clang

script:
  - make
